/**
 * Frozen-snapshot generator. SCF-02 (Phase 2 Plan 03 / RESEARCH §Pattern 2).
 *
 * Turns an `EntityProjection` into a byte-stable TypeScript module
 * (`v1.ts` / `v2.ts`) that the scaffold orchestrator (Plan 07) writes
 * into the per-migration folder alongside `migration.ts`.
 *
 * Design constraints (from RESEARCH §Pattern 2 and §Pitfall 1):
 * - Pure deterministic function: same projection + version → byte-identical
 *   output, independent of input key insertion order. Tested by reversing
 *   `Object.keys` order on equivalent projections and asserting `===`.
 * - No closures, validators, getters, or user source copied through —
 *   the input is already projected to a closed allowlist (Phase 1 DRF-01).
 * - Hardcoded `import { Entity } from 'electrodb';` — never a relative path,
 *   never a `tsconfig.paths` mapping, so the file loads identically from
 *   any consumer location (the test harness, the framework runtime, the
 *   user's app, CI).
 * - All object keys at every nesting level emitted alphabetically.
 * - 2-space indentation, single quotes, LF line endings, trailing `\n`.
 *
 * The scaffold orchestrator (Plan 07) will:
 * 1. Project the user's entity model via `projectEntityModel(...)`.
 * 2. Call `renderFrozenEntitySource({projection, version})` for each side
 *    of the migration (`v1.ts` rendered with the previous projection +
 *    version `'1'`, `v2.ts` with the current projection + version `'2'`).
 * 3. Compute `computeIntegrityHash(rendered)` and store on the migration's
 *    `frozenSnapshots` record (consumed by Phase 7 `validate`).
 *
 * @see README §4 (Quick start: scaffolds v1.ts and v2.ts)
 */
import type { EntityProjection, ProjectedAttribute, ProjectedIndex, ProjectedKey } from '../safety/fingerprint-projection.js';

const HEADER_PREAMBLE = [
  '// AUTO-GENERATED by electrodb-migrations. DO NOT EDIT.',
  '// Editing this file invalidates the integrity hash and will fail `validate` (Phase 7).',
  '// Regenerate with `electrodb-migrations create --regenerate <id>` after rebases.',
] as const;

const IMPORT_LINE = "import { Entity } from 'electrodb';" as const;

export interface RenderFrozenEntitySourceArgs {
  projection: EntityProjection;
  version: string;
}

/**
 * Render an `EntityProjection` to a deterministic, parseable TypeScript
 * source file. Output shape:
 *
 *     // AUTO-GENERATED by electrodb-migrations. DO NOT EDIT.
 *     // ...
 *     // ...
 *     import { Entity } from 'electrodb';
 *
 *     export const <EntityName> = new Entity({
 *       model: { entity: '...', service: '...', version: '...' },
 *       attributes: { ... },
 *       indexes: { ... },
 *     });
 */
export function renderFrozenEntitySource(args: RenderFrozenEntitySourceArgs): string {
  const { projection, version } = args;
  const lines: string[] = [];
  for (const h of HEADER_PREAMBLE) lines.push(h);
  lines.push(IMPORT_LINE);
  lines.push('');
  lines.push(`export const ${projection.entity} = new Entity({`);
  // model — alphabetical: entity, service, version
  lines.push(`  model: { entity: ${quote(projection.entity)}, service: ${quote(projection.service)}, version: ${quote(version)} },`);
  // attributes — alphabetical
  lines.push('  attributes: {');
  for (const name of Object.keys(projection.attributes).sort()) {
    const attr = projection.attributes[name];
    if (!attr) continue;
    emitAttributeEntry(lines, name, attr, '    ');
  }
  lines.push('  },');
  // indexes — alphabetical
  lines.push('  indexes: {');
  for (const name of Object.keys(projection.indexes).sort()) {
    const idx = projection.indexes[name];
    if (!idx) continue;
    emitIndexEntry(lines, name, idx, '    ');
  }
  lines.push('  },');
  lines.push('});');
  return `${lines.join('\n')}\n`;
}

/* --------------------------------------------------------------------- */
/* Emitters                                                               */
/* --------------------------------------------------------------------- */

/**
 * Emit a single named attribute entry inline if it fits, otherwise
 * multi-line. The locked field sequence is:
 *   type, required, hidden, readOnly, field
 * followed by alphabetical-among-optional:
 *   enumArray, items, padding, properties, template
 */
function emitAttributeEntry(lines: string[], name: string, attr: ProjectedAttribute, indent: string): void {
  const inline = inlineAttribute(attr);
  const oneLine = `${indent}${name}: ${inline},`;
  if (!hasNestedShape(attr) && oneLine.length <= 80) {
    lines.push(oneLine);
    return;
  }
  // Multi-line emission
  lines.push(`${indent}${name}: {`);
  emitAttributeBody(lines, attr, `${indent}  `);
  lines.push(`${indent}},`);
}

function hasNestedShape(attr: ProjectedAttribute): boolean {
  return attr.properties !== undefined || (attr.items !== undefined && typeof attr.items !== 'string');
}

function emitAttributeBody(lines: string[], attr: ProjectedAttribute, indent: string): void {
  // Locked sequence (always present per ProjectedAttribute shape)
  lines.push(`${indent}type: ${emitType(attr.type)},`);
  lines.push(`${indent}required: ${attr.required},`);
  lines.push(`${indent}hidden: ${attr.hidden},`);
  lines.push(`${indent}readOnly: ${attr.readOnly},`);
  lines.push(`${indent}field: ${quote(attr.field)},`);
  // Optional alphabetical: enumArray, items, padding, properties, template
  if (attr.enumArray !== undefined) {
    lines.push(`${indent}enumArray: ${emitStringArray(attr.enumArray)},`);
  }
  if (attr.items !== undefined) {
    if (typeof attr.items === 'string') {
      lines.push(`${indent}items: ${quote(attr.items)},`);
    } else {
      lines.push(`${indent}items: {`);
      emitAttributeBody(lines, attr.items, `${indent}  `);
      lines.push(`${indent}},`);
    }
  }
  if (attr.padding !== undefined) {
    lines.push(`${indent}padding: { char: ${quote(attr.padding.char)}, length: ${attr.padding.length} },`);
  }
  if (attr.properties !== undefined) {
    lines.push(`${indent}properties: {`);
    for (const k of Object.keys(attr.properties).sort()) {
      const sub = attr.properties[k];
      if (!sub) continue;
      emitAttributeEntry(lines, k, sub, `${indent}  `);
    }
    lines.push(`${indent}},`);
  }
  if (attr.template !== undefined) {
    lines.push(`${indent}template: ${quote(attr.template)},`);
  }
}

/**
 * Inline single-line form of an attribute (used when no nested shapes
 * and the result fits within 80 chars).
 */
function inlineAttribute(attr: ProjectedAttribute): string {
  const parts: string[] = [];
  parts.push(`type: ${emitType(attr.type)}`);
  parts.push(`required: ${attr.required}`);
  parts.push(`hidden: ${attr.hidden}`);
  parts.push(`readOnly: ${attr.readOnly}`);
  parts.push(`field: ${quote(attr.field)}`);
  if (attr.enumArray !== undefined) parts.push(`enumArray: ${emitStringArray(attr.enumArray)}`);
  if (attr.items !== undefined && typeof attr.items === 'string') {
    parts.push(`items: ${quote(attr.items)}`);
  }
  if (attr.padding !== undefined) {
    parts.push(`padding: { char: ${quote(attr.padding.char)}, length: ${attr.padding.length} }`);
  }
  if (attr.template !== undefined) parts.push(`template: ${quote(attr.template)}`);
  return `{ ${parts.join(', ')} }`;
}

function emitIndexEntry(lines: string[], name: string, idx: ProjectedIndex, indent: string): void {
  lines.push(`${indent}${name}: {`);
  emitIndexBody(lines, idx, `${indent}  `);
  lines.push(`${indent}},`);
}

function emitIndexBody(lines: string[], idx: ProjectedIndex, indent: string): void {
  lines.push(`${indent}type: ${quote(idx.type)},`);
  lines.push(`${indent}pk: ${emitKey(idx.pk)},`);
  if (idx.sk !== undefined) {
    lines.push(`${indent}sk: ${emitKey(idx.sk)},`);
  }
  if (idx.collection !== undefined) {
    if (typeof idx.collection === 'string') {
      lines.push(`${indent}collection: ${quote(idx.collection)},`);
    } else {
      lines.push(`${indent}collection: ${emitStringArray(idx.collection)},`);
    }
  }
}

/**
 * Inline single-line form of a key. Locked field sequence: field, composite,
 * then alphabetical-among-optional: casing, postfix, prefix, template.
 */
function emitKey(key: ProjectedKey): string {
  const parts: string[] = [];
  parts.push(`field: ${quote(key.field)}`);
  parts.push(`composite: ${emitStringArray(key.composite)}`);
  if (key.casing !== undefined) parts.push(`casing: ${quote(key.casing)}`);
  if (key.postfix !== undefined) parts.push(`postfix: ${quote(key.postfix)}`);
  if (key.prefix !== undefined) parts.push(`prefix: ${quote(key.prefix)}`);
  if (key.template !== undefined) parts.push(`template: ${quote(key.template)}`);
  return `{ ${parts.join(', ')} }`;
}

function emitType(type: string | readonly string[]): string {
  if (typeof type === 'string') return quote(type);
  return emitStringArray(type);
}

function emitStringArray(items: readonly string[]): string {
  if (items.length === 0) return '[]';
  return `[${items.map(quote).join(', ')}]`;
}

/**
 * Single-quoted string literal with `\` and `'` escaped.
 */
function quote(s: string): string {
  return `'${s.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
}
