import { mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { renderFrozenEntitySource } from '../../../src/scaffold/frozen-snapshot.js';
import type { EntityProjection } from '../../../src/safety/fingerprint-projection.js';

let dir: string;

beforeEach(() => {
  dir = mkdtempSync(join(tmpdir(), 'edbm-frozen-snapshot-test-'));
});

afterEach(() => {
  rmSync(dir, { recursive: true, force: true });
});

/**
 * Build a small canonical projection. The factory inserts keys in
 * **alphabetical** order; tests that need reverse-ordered insertion
 * build their object literals inline.
 */
function projectionUserSimple(): EntityProjection {
  return {
    entity: 'User',
    service: 'app',
    attributes: {
      email: { type: 'string', required: true, hidden: false, readOnly: false, field: 'email' },
      id: { type: 'string', required: true, hidden: false, readOnly: false, field: 'id' },
      status: {
        type: 'string',
        required: false,
        hidden: false,
        readOnly: false,
        field: 'status',
        enumArray: ['active', 'inactive'],
      },
    },
    indexes: {
      byId: {
        type: 'isolated',
        pk: { field: 'pk', composite: ['id'] },
        sk: { field: 'sk', composite: [] },
      },
    },
  };
}

describe('renderFrozenEntitySource — header preamble + import + export shape', () => {
  it('starts with the AUTO-GENERATED three-line preamble', () => {
    const out = renderFrozenEntitySource({ projection: projectionUserSimple(), version: '1' });
    const lines = out.split('\n');
    expect(lines[0]).toBe('// AUTO-GENERATED by electrodb-migrations. DO NOT EDIT.');
    expect(lines[1]).toBe('// Editing this file invalidates the integrity hash and will fail `validate` (Phase 7).');
    expect(lines[2]).toBe('// Regenerate with `electrodb-migrations create --regenerate <id>` after rebases.');
  });

  it('emits `import { Entity } from \'electrodb\';` exactly once at line 4', () => {
    const out = renderFrozenEntitySource({ projection: projectionUserSimple(), version: '1' });
    const lines = out.split('\n');
    expect(lines[3]).toBe("import { Entity } from 'electrodb';");
    const importMatches = out.match(/import \{ Entity \} from 'electrodb';/g) ?? [];
    expect(importMatches.length).toBe(1);
  });

  it('emits `export const <EntityName> = new Entity({` for the named export', () => {
    const out = renderFrozenEntitySource({ projection: projectionUserSimple(), version: '1' });
    expect(out).toMatch(/export const User = new Entity\(\{/);
  });

  it('embeds the version literal in the model block (version=1)', () => {
    const out = renderFrozenEntitySource({ projection: projectionUserSimple(), version: '1' });
    expect(out).toMatch(/version: '1'/);
  });

  it('embeds the version literal in the model block (version=2)', () => {
    const out = renderFrozenEntitySource({ projection: projectionUserSimple(), version: '2' });
    expect(out).toMatch(/version: '2'/);
    expect(out).not.toMatch(/version: '1'/);
  });
});

describe('renderFrozenEntitySource — model block alphabetical', () => {
  it('emits model keys in alphabetical order: entity, service, version', () => {
    const out = renderFrozenEntitySource({ projection: projectionUserSimple(), version: '1' });
    const entityIdx = out.indexOf("entity: 'User'");
    const serviceIdx = out.indexOf("service: 'app'");
    const versionIdx = out.indexOf("version: '1'");
    expect(entityIdx).toBeGreaterThan(-1);
    expect(serviceIdx).toBeGreaterThan(-1);
    expect(versionIdx).toBeGreaterThan(-1);
    expect(entityIdx).toBeLessThan(serviceIdx);
    expect(serviceIdx).toBeLessThan(versionIdx);
  });
});

describe('renderFrozenEntitySource — determinism', () => {
  it('produces byte-identical output for two equivalent projections with reordered attribute keys', () => {
    const p1: EntityProjection = {
      entity: 'User',
      service: 'app',
      attributes: {
        status: { type: 'string', required: false, hidden: false, readOnly: false, field: 'status' },
        id: { type: 'string', required: true, hidden: false, readOnly: false, field: 'id' },
        email: { type: 'string', required: true, hidden: false, readOnly: false, field: 'email' },
      },
      indexes: {
        byId: {
          type: 'isolated',
          pk: { field: 'pk', composite: ['id'] },
          sk: { field: 'sk', composite: [] },
        },
      },
    };
    const p2: EntityProjection = {
      entity: 'User',
      service: 'app',
      attributes: {
        email: { type: 'string', required: true, hidden: false, readOnly: false, field: 'email' },
        id: { type: 'string', required: true, hidden: false, readOnly: false, field: 'id' },
        status: { type: 'string', required: false, hidden: false, readOnly: false, field: 'status' },
      },
      indexes: {
        byId: {
          type: 'isolated',
          pk: { field: 'pk', composite: ['id'] },
          sk: { field: 'sk', composite: [] },
        },
      },
    };
    expect(renderFrozenEntitySource({ projection: p1, version: '1' })).toBe(
      renderFrozenEntitySource({ projection: p2, version: '1' }),
    );
  });

  it('produces byte-identical output for two equivalent projections with reordered index keys', () => {
    const p1: EntityProjection = {
      entity: 'User',
      service: 'app',
      attributes: {
        id: { type: 'string', required: true, hidden: false, readOnly: false, field: 'id' },
      },
      indexes: {
        byOrg: {
          type: 'isolated',
          pk: { field: 'gsi1pk', composite: ['orgId'] },
        },
        byId: {
          type: 'isolated',
          pk: { field: 'pk', composite: ['id'] },
        },
      },
    };
    const p2: EntityProjection = {
      entity: 'User',
      service: 'app',
      attributes: {
        id: { type: 'string', required: true, hidden: false, readOnly: false, field: 'id' },
      },
      indexes: {
        byId: {
          type: 'isolated',
          pk: { field: 'pk', composite: ['id'] },
        },
        byOrg: {
          type: 'isolated',
          pk: { field: 'gsi1pk', composite: ['orgId'] },
        },
      },
    };
    expect(renderFrozenEntitySource({ projection: p1, version: '1' })).toBe(
      renderFrozenEntitySource({ projection: p2, version: '1' }),
    );
  });

  it('places attributes in alphabetical order in the output even when input is reverse-sorted', () => {
    const out = renderFrozenEntitySource({ projection: projectionUserSimple(), version: '1' });
    // attribute keys at the top of attributes block
    const emailIdx = out.indexOf('email: {');
    const idIdx = out.indexOf('id: {');
    const statusIdx = out.indexOf('status: {');
    expect(emailIdx).toBeGreaterThan(-1);
    expect(idIdx).toBeGreaterThan(-1);
    expect(statusIdx).toBeGreaterThan(-1);
    expect(emailIdx).toBeLessThan(idIdx);
    expect(idIdx).toBeLessThan(statusIdx);
  });

  it('is idempotent across multiple invocations on the same projection', () => {
    const p = projectionUserSimple();
    const first = renderFrozenEntitySource({ projection: p, version: '1' });
    const second = renderFrozenEntitySource({ projection: p, version: '1' });
    const third = renderFrozenEntitySource({ projection: p, version: '1' });
    expect(first).toBe(second);
    expect(second).toBe(third);
  });
});

describe('renderFrozenEntitySource — attribute fields', () => {
  it('emits required: true for required attributes', () => {
    const out = renderFrozenEntitySource({ projection: projectionUserSimple(), version: '1' });
    expect(out).toMatch(/required: true/);
  });

  it('emits enumArray as a single-quoted inline array when present', () => {
    const out = renderFrozenEntitySource({ projection: projectionUserSimple(), version: '1' });
    expect(out).toMatch(/enumArray: \['active', 'inactive'\]/);
  });

  it('omits enumArray on attributes that lack it', () => {
    const out = renderFrozenEntitySource({ projection: projectionUserSimple(), version: '1' });
    // id and email do not have enumArray; check the email block
    const emailBlock = out.slice(out.indexOf('email: {'), out.indexOf('id: {'));
    expect(emailBlock).not.toMatch(/enumArray/);
  });

  it('emits all four boolean fields plus type and field on every attribute', () => {
    const out = renderFrozenEntitySource({ projection: projectionUserSimple(), version: '1' });
    // Each attribute should appear with its locked field sequence; check 'id'
    const idBlock = out.slice(out.indexOf('id: {'), out.indexOf('status: {'));
    expect(idBlock).toMatch(/type: 'string'/);
    expect(idBlock).toMatch(/required: true/);
    expect(idBlock).toMatch(/hidden: false/);
    expect(idBlock).toMatch(/readOnly: false/);
    expect(idBlock).toMatch(/field: 'id'/);
  });
});

describe('renderFrozenEntitySource — indexes', () => {
  it('emits pk and sk when sk is present', () => {
    const out = renderFrozenEntitySource({ projection: projectionUserSimple(), version: '1' });
    expect(out).toMatch(/pk:\s*\{[^}]*field:\s*'pk'/);
    expect(out).toMatch(/sk:\s*\{[^}]*field:\s*'sk'/);
  });

  it('omits sk when absent on the index', () => {
    const p: EntityProjection = {
      entity: 'User',
      service: 'app',
      attributes: {
        id: { type: 'string', required: true, hidden: false, readOnly: false, field: 'id' },
      },
      indexes: {
        byId: {
          type: 'isolated',
          pk: { field: 'pk', composite: ['id'] },
        },
      },
    };
    const out = renderFrozenEntitySource({ projection: p, version: '1' });
    // No 'sk:' key should appear at all in this output.
    expect(out).not.toMatch(/\bsk:\s*\{/);
  });

  it('emits empty composite arrays as []', () => {
    const out = renderFrozenEntitySource({ projection: projectionUserSimple(), version: '1' });
    // sk has composite: []
    expect(out).toMatch(/composite:\s*\[\]/);
  });

  it('emits inline composite arrays for short lists', () => {
    const out = renderFrozenEntitySource({ projection: projectionUserSimple(), version: '1' });
    expect(out).toMatch(/composite:\s*\['id'\]/);
  });
});

describe('renderFrozenEntitySource — formatting', () => {
  it('uses single quotes throughout (no double-quoted string literals)', () => {
    const out = renderFrozenEntitySource({ projection: projectionUserSimple(), version: '1' });
    // The header preamble may contain backticks or apostrophes; strip the comment lines
    // and check the code body has no double-quoted strings.
    const codeBody = out
      .split('\n')
      .filter((l) => !l.trim().startsWith('//'))
      .join('\n');
    expect(codeBody).not.toMatch(/"/);
  });

  it('uses LF line endings (no CR)', () => {
    const out = renderFrozenEntitySource({ projection: projectionUserSimple(), version: '1' });
    expect(out).not.toMatch(/\r/);
  });

  it('ends with exactly one trailing newline', () => {
    const out = renderFrozenEntitySource({ projection: projectionUserSimple(), version: '1' });
    expect(out.endsWith('\n')).toBe(true);
    expect(out.endsWith('\n\n')).toBe(false);
  });

  it('uses 2-space indentation', () => {
    const out = renderFrozenEntitySource({ projection: projectionUserSimple(), version: '1' });
    // top-level keys inside `new Entity({...})` should be indented by 2 spaces
    expect(out).toMatch(/^ {2}model: \{/m);
    expect(out).toMatch(/^ {2}attributes: \{/m);
    expect(out).toMatch(/^ {2}indexes: \{/m);
  });
});

describe('renderFrozenEntitySource — TypeScript syntactic validity', () => {
  it('output round-trips via jiti to a module whose named export has the right model fields', async () => {
    const projection = projectionUserSimple();
    const out = renderFrozenEntitySource({ projection, version: '1' });
    const tmpFile = join(dir, 'v1.ts');
    writeFileSync(tmpFile, out, 'utf8');
    const { createJiti } = await import('jiti');
    const jiti = createJiti(import.meta.url, { tryNative: true });
    const mod = (await jiti.import(tmpFile)) as Record<string, { model: { entity: string; service: string; version: string } }>;
    expect(mod.User).toBeDefined();
    expect(mod.User.model.entity).toBe('User');
    expect(mod.User.model.service).toBe('app');
    expect(mod.User.model.version).toBe('1');
  });

  it('emits valid TypeScript syntax (parseable with the TypeScript compiler)', async () => {
    const projection = projectionUserSimple();
    const out = renderFrozenEntitySource({ projection, version: '2' });
    const ts = await import('typescript');
    const sf = ts.createSourceFile('frozen.ts', out, ts.ScriptTarget.ES2022, /* setParentNodes */ true);
    // No parse-error diagnostics should be attached
    const parseDiagnostics = (sf as unknown as { parseDiagnostics?: ReadonlyArray<unknown> }).parseDiagnostics ?? [];
    expect(parseDiagnostics).toEqual([]);
  });
});
